import os
import pytz
import datetime
from .email import *
from .logging import *
from .database import *
from pathlib import Path
from decimal import Decimal
from .app_middleware import *
from datetime import timedelta
from dotenv import load_dotenv


load_dotenv()  # loads .env
BASE_DIR = Path(__file__).resolve().parent.parent  # points to project root
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = bool(os.environ.get('DJANGO_DEBUG', default=False))
ALLOWED_HOSTS = ["*"]

ROOT_URLCONF = 'backend.urls'
WSGI_APPLICATION = 'backend.wsgi.application'

# Booking & Pricing
BASIC_SLOT_PRICE = Decimal('85000.00')
STANDARD_SLOT_PRICE = Decimal('125000.00')
MONTHLY_SLOT_PRICE = Decimal('25000.00')
DELIVERY_FEE = Decimal('3000.00')  # Additional fee for delivery option
REFERRAL_BONUS = Decimal('2000.00')  # New referral bonus
lagos = pytz.timezone('Africa/Lagos')
BOOKING_CUTOFF_DATETIME = lagos.localize(
    datetime.datetime(2025, 6, 5, 19, 0, 0))


# Slot Limits
MAX_SLOTS_PER_TRANSACTION = 4  # Max slots per Flutterwave transaction
MAX_TOTAL_SLOTS_PER_USER = 7  # Overall max slots a user can book


# Flutterwave webhook secret
FLUTTERWAVE_SECRET_KEY = os.environ.get("FLUTTERWAVE_SECRET_KEY")
FLUTTERWAVE_WEBHOOK_SECRET = os.environ.get("FLUTTERWAVE_WEBHOOK_SECRET")

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Lagos'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# STORAGES = {
#     "default": {
#         "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
#     },
# }

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# You don't have to use api.users.models.User
# The format '<app_label>.<model_name>' is used to refer to the model
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'backend.config.cookies.CookieJWTAuthentication'
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
    },
    'USE_TZ': True,  # Make sure DRF respects timezone-aware datetime
    'DATETIME_FORMAT': "%Y-%m-%d %H:%M:%S",  # Optional: customize format
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_BLACKLIST_ENABLED': True,
}

# Depends on ACCESS_TOKEN_LIFETIME and REFRESH_TOKEN_LIFETIME above
ACCESS_TOKEN_LIFETIME = 15 * 60  # 15 minutes in secs
REFRESH_TOKEN_LIFETIME = 1 * 24 * 60 * 60  # 1 day in seconds


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

# Use database-backed sessions (default)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # age of session 2 weeks in seconds
SESSION_COOKIE_SECURE = False  # Use HTTPS if set to True
SESSION_COOKIE_HTTPONLY = True  # Set the cookie to be accessible only via HTTP

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Internationalization: https://docs.djangoproject.com/en/5.2/topics/i18n/
# Static files (CSS, JavaScript, Images): https://docs.djangoproject.com/en/5.2/howto/static-files/
# Default primary key field type: https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# Password validation:https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
"""
